spring:
  servlet:
    multipart:
      location: C:/dev/lecture_code/spring-boot/chap07-file-upload
#      yml??? ? ???? ????? ??? ? ??? ???? ?? ????? ???? ??? ??.
      max-file-size: 10MB
      max-request-size: 10MB
